-- Create forecasts table for storing prediction results
CREATE TABLE IF NOT EXISTS forecasts (
    id SERIAL PRIMARY KEY,
    product_sku VARCHAR(255) NOT NULL,
    forecast_date DATE NOT NULL,
    predicted_sales INTEGER NOT NULL,
    current_sales INTEGER,
    current_date_col DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Add index for faster queries
    CONSTRAINT forecasts_unique UNIQUE (product_sku, forecast_date, created_at)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_forecasts_product_sku ON forecasts(product_sku);
CREATE INDEX IF NOT EXISTS idx_forecasts_forecast_date ON forecasts(forecast_date);
CREATE INDEX IF NOT EXISTS idx_forecasts_created_at ON forecasts(created_at DESC);

-- Add comment
COMMENT ON TABLE forecasts IS 'Stores sales forecasts generated by the ML model';
